### ISSUE TITLE
Power Calc

### ISSUE THREAD

**Issue by ipod86** [ioBroker/AdapterRequests#814]
Ich habe eben von einem ziemlich coolen Addon für HA gelesen.
Das wäre auch ein klasse Adapter für den iobroker.

Ich Poste einfach mal die Beschreibung:

**Power Calc – Stromverbrauch ohne Hilfsmittel messen**

Mit Power Calc lässt sich der Stromverbrauch vieler Geräte ermitteln, ohne dass dazu Energiemessgeräte wie eine smarte Steckdose oder der von mir sehr geschätzte Shelly 3EM notwendig wäre.

Power Calc kennt viele Geräte wie z. B. Philips Hue Lights, IKEA Tradfri, innr, WLED Anwendungen, aber auch andere Verbraucher, wenn man diesen einen fixen Stromverbrauch zuordnen kann.

Power Calc findet kompatible Geräte direkt
Weiß man etwa, dass die Beleuchtung in der Küche 32 Watt verbraucht, weil sie aus 8 LED Spots mit 4 Watt Leistung besteht, kann man daraus einen virtuellen Verbrauchssensor erstellen. Dieser erfasst dann automatisch den Verbrauch, wenn die Beleuchtung in Betrieb ist.

Selbst gedimmte Leuchtmittel lassen sich damit erstaunlich genau erfassen, wenn man deren Verbrauch bei verschiedenen Helligkeitsstufen vorher einmal mit einem Verbrauchsmessgerät erfasst und eine entsprechende Umrechnung integriert, die etwa so aussehen kann:

```
sensor:
  - platform: powercalc
    entity_id: light.wohnzimmer_deckenbeleuchtung
    linear:
      calibrate:
        - 1 -> 0.3
        - 10 -> 1.25
        - 50 -> 3.50
        - 100 -> 6.8
        - 255 -> 15.3
```
        
So lassen sich auch nicht lineare Verbräuche, was besonders bei klassischen Glühlampen mit Glühfaden der Fall ist, die gedimmt werden, mit Power Calc erfassen.
